# Generated by Django 6.0.1 on 2026-02-20 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galery',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='galety_media/'),
        ),
    ]
