# Generated by Django 6.0.1 on 2026-02-21 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_galery_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galery',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='galery_media/'),
        ),
    ]
