# Generated by Django 6.0.1 on 2026-02-22 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_galery_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfoliofile',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='portfolio_media/'),
        ),
        migrations.AlterField(
            model_name='portfoliofile',
            name='type',
            field=models.CharField(choices=[('File', 'Файл'), ('Link', 'Посилання')], max_length=10),
        ),
        migrations.AlterField(
            model_name='portfoliofile',
            name='url',
            field=models.URLField(blank=True, max_length=100, null=True),
        ),
    ]
