# Generated by Django 6.0.1 on 2026-02-22 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_portfoliofile_file_alter_portfoliofile_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfoliofile',
            name='type',
            field=models.CharField(choices=[('File', 'Файл'), ('Link', 'Посилання')], max_length=16),
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(choices=[('User', 'Користувач'), ('Admin', 'Адмін'), ('Moderator', 'Модератор')], max_length=32),
        ),
    ]
