# Generated by Django 6.0.1 on 2026-03-07 00:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_category_anonts_event_material_message_profile_topic'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='anonts',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['date_start']},
        ),
        migrations.AddField(
            model_name='event',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='date_end',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='date_start',
            field=models.DateTimeField(),
        ),
    ]
